// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzw8ETft-GHpCQyiti9QAPNbwizVUgVJI',
    appId: '1:535119367767:android:93c97b56c64e4bbe741d12',
    messagingSenderId: '535119367767',
    projectId: 'gastos-e4e05',
    databaseURL: 'https://gastos-e4e05-default-rtdb.firebaseio.com',
    storageBucket: 'gastos-e4e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqddEk13v2skXUNODnTm0x8tOEZx1G8c',
    appId: '1:535119367767:ios:56dec16186cc2bfc741d12',
    messagingSenderId: '535119367767',
    projectId: 'gastos-e4e05',
    databaseURL: 'https://gastos-e4e05-default-rtdb.firebaseio.com',
    storageBucket: 'gastos-e4e05.firebasestorage.app',
    androidClientId: '535119367767-krs3gipvsk8bgk9ecq6llsn71b50tg1u.apps.googleusercontent.com',
    iosClientId: '535119367767-7veqjabo1vi91dchsid6cm1h1pifrp8g.apps.googleusercontent.com',
    iosBundleId: 'com.henryllamuca.gastos',
  );

}